version: "3"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    networks:
      - sales-network
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=auth-db
    ports:
      - "5432:5432"

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=product-db
    ports:
      - "5433:5432"

  sales-db:
    image: mongo
    container_name: sales-db
    networks:
      - sales-network
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"

  sales-rabbit:
    image: rabbitmq:3.6-management
    container_name: sales-rabbit
    networks:
      - sales-network
    restart: always
    ports:
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"

  auth-api:
    build: './auth-api'
    container_name: auth-api
    networks:
      - sales-network
    environment:
      - PORT=8080
    ports:
      - "8080:8080"

  product-api:
    build: './product-api'
    container_name: product-api
    networks:
      - sales-network
    environment:
      - PORT=8081
    ports:
      - "8081:8081"

  sales-api:
    build: './sales-api'
    container_name: sales-api
    networks:
      - sales-network
    environment:
      - PORT=8082
    ports:
      - "8082:8082"

networks:
  sales-network:
    driver: bridge