version: "3"
services:
  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=product-db
    ports:
      - "5433:5432"
  product-rabbit:
    image: rabbitmq:3.11.0-management
    container_name: sales-rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
      - "4369:4369"
